# Generated by Django 3.0.3 on 2020-04-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillbook_app', '0002_auto_20200406_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='photo',
        ),
    ]
