# Generated by Django 3.0.3 on 2020-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200327_0440'),
        ('skillbook_app', '0002_auto_20200327_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='users.Profile'),
        ),
    ]
