# Generated by Django 3.0.3 on 2020-04-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillbook_app', '0003_auto_20200406_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
    ]
